import React from 'react';

const PaymentButton = () => {
  const loadRazorpayScript = () => {
    return new Promise((resolve) => {
      const script = document.createElement('script');
      script.src = 'https://checkout.razorpay.com/v1/checkout.js';
      script.onload = () => {
        resolve(true);
      };
      script.onerror = () => {
        resolve(false);
      };
      document.body.appendChild(script);
    });
  };

  const handlePayment = async () => {
    const res = await loadRazorpayScript();

    if (!res) {
      alert('Razorpay SDK failed to load. Are you online?');
      return;
    }

    // Create an order by calling your backend
    const result = await fetch('http://localhost:3000/create-order', {
      method: 'POST',
      body: JSON.stringify({ amount: 2400, currency: 'INR' }), // Amount in INR (₹500)
      headers: {
        'Content-Type': 'application/json',
      },
    });

    const { orderId } = await result.json();

    if (!orderId) {
      alert('Unable to create order. Please try again.');
      return;
    }

    // Configure payment options
    const options = {
      key: 'rzp_live_F37H437Co9Ftpn', // Enter the Key ID generated from Razorpay Dashboard
      amount: 240000, // Amount in smallest unit (50000 paise = ₹500)
      currency: 'INR',
      name: 'Your Company Name',
      description: 'Test Transaction',
      order_id: orderId, // Generated by backend
      handler: async (response) => {
        const paymentData = {
          razorpayPaymentId: response.razorpay_payment_id,
          razorpayOrderId: response.razorpay_order_id,
          razorpaySignature: response.razorpay_signature,
        };

        // Post the payment data to your backend for verification
        const verifyRes = await fetch('http://localhost:3000/verify-payment', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(paymentData),
        });

        const result = await verifyRes.json();

        if (result.success) {
          alert('Payment successful!');
        } else {
          alert('Payment verification failed!');
        }
      },
      prefill: {
        name: 'Your Customer Name',
        email: 'customer.email@example.com',
        contact: '9999999999',
      },
      theme: {
        color: '#F37254',
      },
    };

    const paymentObject = new window.Razorpay(options);
    paymentObject.open();
  };

  return (
    <button className='bg-sky-500 rounded-lg px-2 py-1 text-white font-semibold text-sm cursor-pointer' onClick={handlePayment}>
      Buy Now
    </button>
  );
};

export default PaymentButton;
